### ISSUE TITLE
SameSite cookie attribute has been blocked

### ISSUE THREAD

**Issue by pierot** [noticeable-app/noticeable-widget#1]
An embedded Noticeable widget spawns following warnings in the console:

> A cookie associated with a cross-site resource at http://noticeable.io/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by lpellegr** [comment]
@pierot Thanks again for this report.

The issue seems related to cookies that are generated by Google Analytics and Cloudflare. The current Noticeable widget does not use cookies but locale storage to store users reading state. 

I will investigate what can be done but this issue should have no impact on how the widget behaves.

**Comment by pierot** [comment]
Thanks!

---

Pieter Michels
+32 499 20 76 14
pieter@noort.be
noort.be
